### ISSUE TITLE
System pre-requisite to run this project

### ISSUE THREAD

**Issue by Hafsa-Masroor** [mandarjoshi90/coref#47]
I am using Windows 10 OS. What environment is required to setup & run this project on my machine? 

PS: Anaconda3 is already Installed. What else is required to execute the given python/shell cmds in Setup section?

**Comment by tollefj** [comment]
I suggest you to use WSL and run this in a bash shell, as it is required in order to compile the necessary TF sources: https://github.com/mandarjoshi90/coref/blob/bd04f2e19b9dcc0b8bba848a335e4af3be50741c/setup_all.sh#L7

You may want to try building from source as well:
`g++ -std=c++11 -shared coref_kernels.cc -o coref_kernels.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2` (as fetched from the original repo by K. Lee: https://github.com/kentonl/e2e-coref/blob/master/setup_all.sh)
