### ISSUE TITLE
Input Format

### ISSUE THREAD

**Issue by abhinandansrivastava** [mandarjoshi90/coref#9]
Hi Mandar,

Thanks for this repo.

I am using the pretrained model. If I have a set of sentences in txt format how should I predict the coref. Is there any method to directly convert my sentences in txt format into the required format that model need as an input?

**Comment by mandarjoshi90** [comment]
Hi Abhinandan,
I have't written a script for this, but it should be fairly simple. The `Batched Prediction Instructions
` section in the README has details about the format. Please let me know if you have questions.

**Comment by mandarjoshi90** [comment]
On second thought, this might be a useful script that you might be able to use as a starting point. I'm closing this for now. Please feel free to re-open if you have more questions.
https://github.com/mandarjoshi90/coref/blob/master/gap_to_jsonlines.py

**Comment by Harika-3196** [comment]
> On second thought, this might be a useful script that you might be able to use as a starting point. I'm closing this for now. Please feel free to re-open if you have more questions.
> https://github.com/mandarjoshi90/coref/blob/master/gap_to_jsonlines.py


Hi @mandarjoshi90 

First of all thanks for this script . As @abhinandansrivastava  said even i had a text file where each row having text in tsv file .when i run this script i get the following key error


` a_start, a_end =  datum['A-offset'],  datum['A-offset'] + len(datum['A'])
KeyError: 'A-offset' `

I would like to know how can I get the column **A**  and **A-offset **.  

my input tsv file looks like this

index	Text
1	because where you need you just set the time to it . what you do . bell et one good . were you to censorious ? you think it again , to take nice for nifa a bit waiting to with bush you actually think you rhinoceros antigonish , which will never happen where you love .
2	the shires of toth bush today outcome with me . yes , that would be great . how about sunshade ? that trophies ? i know . 

> '

It would be really thankful if you can help me with this problem

**Comment by flackbash** [comment]
Hi @mandarjoshi90,
could you provide some more info on that?

I would like to perform coreference resolution over custom data. So all I have are plain sentences.

As far as I can see, `gap_to_jsonlines.py` takes an input tsv and a vocab file. The tsv file already contains additional information (`A-offset`, `B-offset`, `Pronoun-offset`, etc) but it does not seem to be documented anywhere how to get this information or what information exactly that is. It is also unclear what format the vocab file should have.

I understand, this is not the main purpose of this code, but I think providing some documentation on how to get from plain custom text to the required input format for `predict.py` would be a great help for anyone who would like to apply your system on their own datasets. It certainly would be a great help for me :)

**Comment by mandarjoshi90** [comment]
Hi Natalie,
I'll try to put something together. A quick answer is that you need to create a `jsonlines` file with the input tokenized using the BERT tokenizer and other information such as the (natural language) sentence and subword maps. See the example here for the format:

https://github.com/mandarjoshi90/coref#batched-prediction-instructions

The BERT-tokenized input text goes into the `sentences` key. Each element of "sentences" is a piece of tokenized text (possibly with multiple natural language sentences) less than 512 subwords. If your document has more than 512 subwords, you'll need to add more elements to `sentences`. You don't really need the pronoun offsets. 

The model will add a key called `predicted_clusters` to the output `jsonlines` file where each element of the value is a cluster and each element of the cluster is a span in the input. 

Please let me know if you have questions.
